config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'emotions#index'
    resources :emotions do
    resources :events
  end
end

app/models/emotion.rb
class Emotion < ActiveRecord::Base
  has_many :events
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :emotion
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/emotions_controller.rb
class EmotionsController < ApplicationController
  def index
    @emotions = Emotion.all
  end

  def show
    @emotion = Emotion.find(params[:id])
    @event = Event.find(params[:id])
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
before_action :authenticate_user!, only: [:new]
 def new
   @emotion = Emotion.find(params[:region_id])
   @event = Event.new
 end

 def create
   @emotion = Emotion.find(params[:region_id])
   @emotion.events.create( event_params )
   redirect_to emotion_path(@emotion)
 end

 def show
  #  @emotion = Emotion.find(params[:id])
   @event = Event.find(params[:id])
 end

 def edit
   @emotion = Emotion.find(params[:region_id])
   @event = Event.find(params[:id])
 end

 def update
  @emotion = Emotion.find(params[:region_id])
   @event = Event.find(params[:id])
   @Event.update(event_params)
   redirect_to event_path(@event)
 end

 def destroy
   @event = Event.find(params[:id])
   @event.destroy
   redirect_to events_path(@emotion)
 end

 def events_params
 params.require(:incident).permit(:title, :location, :datetime, :emotion_level, :free_food, :free_drink)
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/emotions/index.html.erb
<!-- Emotion Index / Splash Page -->
  <div class="mobilecontent">
  <div class="emo-index" id="prompt">
  <h1>What kind of event would you like to attend?</h1>
  </div>

    <% @emotions.each do |emotion| %>
    <a href="/emotions/<%=emotion.id%>">
      <div class="emotion-name" id="emo<%=emotion.id%>"  >
        <div class="emo-index">
          <h1><%= emotion.name %></h1>
      </div>
    </a>
  <%end%>
  </div>
</div>

app/views/emotions/show.html.erb
<!-- show emotions, and events by that emotion -->
<div id="map">
</div>

  <% @emotion.events.each do |event| %>
    <div class="emo-index events event<%=event.emotion_id%>">
        <li> <%= link_to "#{event.title}", emotion_event_path(@emotion, event), class: "event-link event-header" %></li>
        <li><%= "#{event.datetime.strftime("%I:%M%p")}" %>
          <% if @event.free_food %>
            <i class="fa fa-cutlery"></i>
            <% else %>
          <% end %>

          <% if @event.free_drink %>
            <i class="fa fa-glass"></i> </br>
            <% else %>
          <% end %>
        </li>
        <li> <%= "#{event.location}" %> </li>
    </div>
  <% end %>


<script type="text/javascript">

function initMap() {
 map = new google.maps.Map(document.getElementById('map'), {
   center: {lat: 38.9407, lng: -77.0164},
   zoom: 11
 });

 var geocoder = new google.maps.Geocoder();

 //this is a closure. a closure is a function that creates a function that remembers
 //the environemnt in which it was created. Here, the inner function "remembers" that
 //the title is the specific title that was passed to createCallbackFunction.
 //this way it doesn't look for a variable named "title" that could have changed
 //in value.
 var createCallbackFunction = function(title, id) {
   var callback = function(results) {
     //check if there is a result, if so use the first result returned by geocode
     //results is a list of search results based on how google defined it
     if(results[0]){
       //this is where position is in results
       var myLatLng = results[0].geometry.location;
       var marker = new google.maps.Marker({
         position: myLatLng,
         map: map,
         title: title
       });

       //add click event to marker to change url
       marker.addListener('click', function() {
         var url = window.location.href;
         url = url + '/events/' + id;
         window.location.href = url;
      });

     }
   }
   return callback;
 }

<% @emotion.events.each do |event| %>
 var location = "<%= "#{event.location}" %>";
 var title = "<%= "#{event.title}" %>";
 var id = "<%= "#{event.id}" %>";

 geocoder.geocode( { 'address': location}, createCallbackFunction(title, id));
<% end %>
}
   </script>
   <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA-25EOkB2SBSONGOgMdxRPXPtYuHicogk&callback=initMap">
   </script>

app/views/events/index.html.erb
<!-- this is the event index page -->
<h1> Events </h1>

app/views/events/new.html.erb
HI!

app/views/events/show.html.erb
<!-- this is the show page -->
<div id="map">
</div>
  <div class="emo-index eventdetail event<%= @event.emotion_id%>">
      <li><h1><%=@event.title%></h1></li>
      <li> <%= @event.location %></li>
      <li><%= @event.datetime.strftime("%I:%M%p") %>
      <% if @event.free_food %>
        <i class="fa fa-cutlery"></i>
        <% else %>
      <% end %>
      <% if @event.free_drink %>
        <i class="fa fa-glass"></i>
        <% else %>
      <% end %>
      </li>
  </div>
  <div class="emo-index eventdetail event ed event-description<%= @event.emotion_id%>">
    <li><%= @event.description %></li>
    <a class="backbutton" href="/emotions/<%= @event.emotion_id%>"><i class="fa fa-chevron-left"></i></a>
    </div>
    <script type="text/javascript">

function initMap() {
 map = new google.maps.Map(document.getElementById('map'), {
   center: {lat: 38.9047, lng: -77.0164},
   zoom: 8
 });
 var geocoder = new google.maps.Geocoder();

 //this is a closure. a closure is a function that creates a function that remembers
 //the environemnt in which it was created. Here, the inner function "remembers" that
 //the title is the specific title that was passed to createCallbackFunction.
 //this way it doesn't look for a variable named "title" that could have changed
 //in value.
 var createCallbackFunction = function(title, id) {
   var callback = function(results) {
     //check if there is a result, if so use the first result returned by geocode
     //results is a list of search results based on how google defined it
     if(results[0]){
       //this is where position is in results
       var myLatLng = results[0].geometry.location;
       var marker = new google.maps.Marker({
         position: myLatLng,
         map: map,
         title: title
       });
     }
   }
   return callback;
 }

  var location = "<%= @event.location %>";
  var title = "<%= @event.title %>";
  var id = "<%= @event.id %>";

  geocoder.geocode( { 'address': location}, createCallbackFunction(title, id));


}



</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA-25EOkB2SBSONGOgMdxRPXPtYuHicogk&callback=initMap">
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Freevents</title>
  <meta name="viewport" content="initial-scale=1, maximum-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
</head>
<body>

  <nav class="fixed-nav-bar">
  <a href="/"><i class="fa fa-chevron-left nav-link"></i></a>
  <% if current_user %>
  <h3 class="nav-link"><%= link_to 'Signout', destroy_user_session_path, :method => :delete %></h3>
  <% else %>
  <h3 class="nav-link"><%= link_to 'Signup', new_user_registration_path %></h3>
  <h3 class="nav-link"><%= link_to 'Login', new_user_session_path %></h3>
  <% end %>
  </nav>


  <div class= "site-wrapper">
    <div class="content">
      <%= yield %>
    </div>
  </div>
</body>
</html>